### ISSUE TITLE
Compiling on Mac/Clang

### ISSUE THREAD

**Issue by henrixapp** [KarlsruheMIS/KaMIS#23]
When compiling on Mac with clang, following error occurs while compiling dependencies:
```
In file included from /Users/henrik/dev/graph/KaMIS/lib/mis/evolutionary/reduction_evolution.cpp:14:
/Users/henrik/dev/graph/KaMIS/lib/mis/evolutionary/combine/multiway_combine.h:115:98: error: reference to 'partition' is ambiguous
        void apply_k_partition_kahip(MISConfig & config, graph_access & G, separator_pool *pool, partition & part);
                                                                                                 ^
/Users/henrik/dev/graph/KaMIS/lib/mis/evolutionary/separator_pool.h:21:8: note: candidate found by name lookup is 'partition'
struct partition {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/algorithm:3446:1: note: candidate found by name lookup is 'std::partition'
partition(_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
^
1 error generated.
```
and 

```
[  0%] Building CXX object CMakeFiles/libkaffpa.dir/extern/KaHIP/lib/partition/graph_partitioner.cpp.o
In file included from /Users/henrik/dev/graph/KaMIS/extern/KaHIP/lib/partition/graph_partitioner.cpp:10:
In file included from /Users/henrik/dev/graph/KaMIS/extern/KaHIP/lib/partition/graph_partitioner.h:15:
In file included from /Users/henrik/dev/graph/KaMIS/extern/KaHIP/lib/partition/uncoarsening/refinement/refinement.h:13:
In file included from /Users/henrik/dev/graph/KaMIS/extern/KaHIP/lib/partition/uncoarsening/refinement/quotient_graph_refinement/complete_boundary.h:15:
/Users/henrik/dev/graph/KaMIS/extern/KaHIP/lib/partition/uncoarsening/refinement/quotient_graph_refinement/boundary_lookup.h:17:17: error: expected namespace name
using namespace __gnu_cxx;
```

When using g++-11 (installed via homebrew, inspired by https://github.com/KaHIP/KaHIP/issues/5#issuecomment-282549933) KaMIS compiles fine.

**Comment by schulzchristian** [comment]
Hi Henrik,

we are happy to merge any pull request that fixes this.

Best
Christian

**Comment by Hespian** [comment]
I think @darrenstrash fixed this in 275a875d3c62e6fff7aeed77af8a54d07be82062 ?

**Comment by henrixapp** [comment]
Yes, this fixes it partially. The build still fails, because of #27. I forked the repository 6 months ago and removed all KaHIP sources (there are 3 different copies of KaHIP in this repository) and replaced them with one KaHIP submodule (https://github.com/henrixapp/KaMIS/tree/master). If you are interested, I can submit a merge request.

**Comment by henrixapp** [comment]
Ping

**Comment by schulzchristian** [comment]
@ernestine-grossmann is this still an issue after your last update? If so @darrenstrash should we discuss soon?
